# The URL the site will be built for
base_url = "https://nelin.dk"

title = "o.nelin"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    {name = "tags"}
]

[markdown.highlighting]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
error_on_missing_language = true
theme = "everforest-dark"
# There's also light_theme and dark_theme

[extra]

nav_items = [
  {name = "index", url = "/"},

  {name = "projects", url = "/projects/"},
  {name = "posts", url = "/posts/"},
  {name = "about me", url = "/about/"},
]

feet = [
  {name = "git", url = "/", newtab = true},
  {name = "github", url = "https://github.com/0undefined", newtab = true},
  {name = "codeberg", url = "https://codeberg.org/onelin", newtab = true},
]

projects = [
  {name = "daw", icon="solid fa-crow", url = "https://codeberg.org/onelin/daw", description = "A WIP game engine written in C."},
  {name = "giz.sh", icon="brands fa-git-alt", url = "https://github.com/0undefined/giz.sh", description = "Github/Gittea-like git hosting site"},
  {name = "btree", icon="solid fa-code-fork", url = "https://github.com/0undefined/btree", description = "C implementation of the B-Tree datastructure according to CLRS."},
]
